In [4]:
import pandas as pd
df=pd.read_csv("StudentsPerformance-2.csv")
df.head()

,Unnamed: 0,gender,ethnicity,parEdu,lunch,testPrep,math,reading,writing,mathPass
0,0,female,group B,bachelor's degree,standard,none,72,72,74,1
1,1,female,group C,some college,standard,completed,69,90,88,1
2,2,female,group B,master's degree,standard,none,90,95,93,1
3,3,male,group A,associate's degree,free/reduced,none,47,57,44,0
4,4,male,group C,some college,standard,none,76,78,75,1

In [6]:
df.to_csv("StudentsPerformance-3.csv", index=False)