In [25]:
import pandas as pd
df=pd.read_csv("seed.csv")
df.head()

,area,perimeter,compactness,kernelLength,kernelWidth,asymmetry,kernelGroove,species
0,15.26,14.84,0.8710,5.763,3.312,2.221,5.220,1
1,14.88,14.57,0.8811,5.554,3.333,1.018,4.956,1
2,14.29,14.09,0.9050,5.291,3.337,2.699,4.825,1
3,13.84,13.94,0.8955,5.324,3.379,2.259,4.805,1
4,16.14,14.99,0.9034,5.658,3.562,1.355,5.175,1

In [26]:
df.species.value_counts()
df.columns

Index(['area', 'perimeter', 'compactness', 'kernelLength', 'kernelWidth',
       'asymmetry', 'kernelGroove', 'species'],
      dtype='object')

In [35]:
data_X=df[['area', 'perimeter', 'compactness', 'kernelLength', 'kernelWidth',
       'asymmetry', 'kernelGroove']]
data_y=df.species

In [36]:
data_X

,area,perimeter,compactness,kernelLength,kernelWidth,asymmetry,kernelGroove
0,15.26,14.84,0.8710,5.763,3.312,2.221,5.220
1,14.88,14.57,0.8811,5.554,3.333,1.018,4.956
2,14.29,14.09,0.9050,5.291,3.337,2.699,4.825
3,13.84,13.94,0.8955,5.324,3.379,2.259,4.805
4,16.14,14.99,0.9034,5.658,3.562,1.355,5.175
...,...,...,...,...,...,...,...
205,12.19,13.20,0.8783,5.137,2.981,3.631,4.870
206,11.23,12.88,0.8511,5.140,2.795,4.325,5.003
207,13.20,13.66,0.8883,5.236,3.232,8.315,5.056
208,11.84,13.21,0.8521,5.175,2.836,3.598,5.044
209,12.30,13.34,0.8684,5.243,2.974,5.637,5.063

In [37]:
from sklearn.model_selection import train_test_split
train_X,testX,train_y,test_y=train_test_split(data_X,data_y)

In [38]:
from sklearn.neural_network import MLPClassifier

clf=MLPClassifier()
clf.fit(train_X,train_y)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,

MLPClassifier()

In [39]:
p=clf.predict(testX)
print(sum(p==test_y)/len(p))

0.8679245283018868